sudo: true
dist: trusty
language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - MVN_VERSION="3.5.4"
    - MAVEN_OPTS="-Xmx8g -XX:-UseGCOverheadLimit"

before_install:
  - rm ~/.m2/settings.xml
  - unset _JAVA_OPTIONS

before_script:
  - wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${MVN_VERSION}/apache-maven-${MVN_VERSION}-bin.tar.gz
  - tar zxf apache-maven-${MVN_VERSION}-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-${MVN_VERSION}
  - export PATH=$M2_HOME/bin:$PATH
  - mvn --version
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "sudo pip install 'requests[security]'"
  - "sudo pip install -q sphinx==1.8.5"

matrix:
  allow_failures:
    - jdk: openjdk11
    - jdk: oraclejdk11

install:
  - "mvn install -B -f pom-libs.xml -DskipTests=true" #download dependencies

script: 
  - "mvn install -B -f docs/pom.xml -Dtycho.mode=maven -Pdocs"
  - "mvn verify -B -Pproduct -Pdocs -Psdk -Ptest --fail-at-end -T4"


notifications:
  email:
    on_success: never
    on_failure: never
