sudo: true
language: java
jdk: oraclejdk8

python:
  - "2.7"

env:
  global:
    - TRAVIS_PYTHON_VERSION="2.7"
    - MVN_VERION="3.3.9"

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-Xmx8g -XX:-UseGCOverheadLimit'" > ~/.mavenrc

install:
  - "sudo pip install 'requests[security]'"
  - "sudo pip install -q sphinx==1.1.3"
  - "travis_wait mvn install -B -f docs/pom.xml -Dtycho.mode=maven -Pdocs" #build documentation using sphinx
  - "travis_wait mvn install -B -f pom-libs.xml -DskipTests=true" #download dependencies

script: 
  - "travis_wait mvn install -B -Pproduct -Psdk -T 4"

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - /^travis.*$/
